# fly.toml app configuration file generated for smartattendance-ai on 2026-01-21T08:55:55+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smartattendance-ai'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[source]
  type = "github"
  owner = "hieu182603"
  repo = "SmartAttendance"
  path = "ai-service"

[env]
  ALLOW_INSECURE_AUTH = 'true'
  API_KEY = 'dev-api-key-change-in-production'
  DETECTION_THRESHOLD = '0.5'
  DISPLAY = ''
  HOST = '0.0.0.0'
  INSIGHTFACE_HOME = '/app/models'
  LOG_LEVEL = 'INFO'
  MODEL_NAME = 'buffalo_l'
  PORT = '8080'
  QT_QPA_PLATFORM = 'offscreen'
  VERIFICATION_THRESHOLD = '0.6'

[[mounts]]
  source = 'ai_models'
  destination = '/app/models'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '2048'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
